### ISSUE TITLE
Payin Post

### ISSUE THREAD

**Issue by MIACH99** [Mangopay/mangopay2-net-sdk#9]
There must be support for language for culture while we creating payins, currently it requires a parameter of type CountryISO but MangoPay requires a type of language instead of country so when we pass GB,US or any other instead of FR (PayInDirectDebitPostDTO payIn = new PayInDirectDebitPostDTO(user.Id, new Money { Amount = 10000, Currency = CurrencyIso.EUR }, new Money { Amount = 100, Currency = CurrencyIso.EUR }, wallet.Id, "http://www.mysite.com/returnURL/", CountryIso.US, DirectDebitType.GIROPAY);) then there is an exception: {"Message":"One or several required parameters are missing or incorrect. An incorrect resource ID also raises this kind of error.","Type":"param_error","Id":"2414-245-45-67-541","Date":1440223363.0,"errors":{"Culture":"The requested language is not supported"}}

Please resolve this conflict by changing the sdk as soon as possible.

**Comment by hobailey** [comment]
Hi @MIACH99, thanks for flagging this up but it was infact recently reported and fixed with https://github.com/Mangopay/mangopay2-net-sdk/issues/6 and commit https://github.com/Mangopay/mangopay2-net-sdk/commit/0ba7982f82bc4521ac5361210c9d2309af8f495f :-)

**Comment by MIACH99** [comment]
but it was not fixed for all and PayInDirectDebitPostDTO still using CountryISO.

**Comment by hobailey** [comment]
You're absolutely right - I'm sorry for missing this. https://github.com/Mangopay/mangopay2-net-sdk/commit/ce88e1915a9ad8213bd3a9d20062b8643dee9396 just fixes this :-)
